# Generated by Django 4.2.30 on 2026-07-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3', '0002_seed_networks'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contractdeployment',
            name='uniq_deployment_network_address',
        ),
        migrations.AddConstraint(
            model_name='contractdeployment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('network', 'address'), name='uniq_deployment_network_address'),
        ),
    ]
